# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # v6.0.0
    hooks:
    - id: check-added-large-files
    - id: check-json
      types: [file]  # override `types: [json]`
      files: \.(json|ipynb)$
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 3b42b9776870badc9eaffdef9a4a0834b764d87c  # frozen: v2.29.3
    hooks:
    - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 17e12779811926f000bdfa1795f9e3735dd71ac3 # frozen: 0.26
    hooks:
    - id: validate-pyproject
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1 # 26.5.1
    hooks:
    - id: black
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.17.0 # v3.17.0
    hooks:
    - id: reorder-python-imports
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0 # 7.3.0
    hooks:
    - id: flake8
      language_version: python3
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2 # v1.0.2
    hooks:
    - id: sphinx-lint
      types: [rst]
